apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pingpong
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: maxmynter/devopsk8s-pingpong@sha256:43b881ec41cff32cf8150d9240523cfeaa92022359a53574fee4af04819c4e6e
          env:
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  namespace: pingpong
  name: pingpong-svc
spec:
  type: ClusterIP
  selector: 
    app: pingpong
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
