apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: pingpong
  name: pingpong
  annotations:
    networking.knative.dev/ingress.class: "kourier.ingress.networking.knative.dev"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "30s"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/initial-scale: "1"
        autoscaling.knative.dev/window: "30s"
    spec:
      containers:
        - name: pingpong
          image: PONG/PINGPONG
          resources:
            limits:
              cpu: "150m"
          ports:
            - containerPort: 3001
          env:
            - name: APP_PORT
              value: "3001"
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
