apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
data:
    POSTGRES_USER: ENC[AES256_GCM,data:hsk6BUsSYic=,iv:d+HPtYBoB5OWPp7QaODGEGlyfxKZ0UDD0jioelhGc9Q=,tag:baV9juMvxUO4+yEmJ+vxgg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8IqGbw==,iv:Fw705Hh3BM7aKOz2GcBGj1rsilQ6o3sb9dt7mF9XbVw=,tag:LnewH3Lnjo6KXGeml5IsEQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:6T+//xMawlSdO03D,iv:YAxQ7YNGTP6NaF/lcvvmmkMW/TWl/pvv0xLcjJns3Cg=,tag:itapsHxO7dBiSNYm3+eLIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yyjdng93qch2ms6yygterjuwdu33n7tx67mr4f4y29l4ugkwumqtjzexm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTkFpL0RoSUZNSUQ5MEZH
            dzFwalBONW16Q3BieUdFZlU0RHlTS3M4RlJ3CjRzTDJTU0hCNkZXbXByTGZIS2VP
            YW5EYU92NHc5QmFQTFZyQWVINjloRXcKLS0tIDVSMWc2eTlNNWdSTWpVRExzRmEv
            V3p3VHovWmlUYVdNcm9leEdvUVJHbFUKvnFQyv3aZOVNjddyvnS6y+FjeJ2i8Bdx
            dd56W/PmvZai8VrARVVfr3pkNhzYYYYoaMhkDR/P1mSOjbkZt64nkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T16:47:37Z"
    mac: ENC[AES256_GCM,data:EmN+3RlUgJ73FT5UIlRO5Qznmyw5trPTCoKKVi1v+sbq4fMNECY7QOWbhWoVb23FlPQ61S1u63JA78if4/ulxMChZNUoCTHOl42zgz4FZu851izwuDUWO6HLa2ZqeOgAQJE/vG3aS3lYDV37r3x55wfZYiZdzpAZcMLzfX5qezs=,iv:MnUFJl9i/GtvMteed/Zv/afO7/CvBPWsujCpccuMzo8=,tag:m/oT5k4GdySk/d2pGEhgYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.1
