apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: project
data:
    POSTGRES_USER: ENC[AES256_GCM,data:b4+xWutK0Ho=,iv:Fx6KC5rk/nKaClRmPTiBzXrVvdtblfgz5QpJDwddm7M=,tag:mS9DHHefUHlS6WXqllaj2A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:CeSSMQ==,iv:uuS4d4tj5Ixmipvv+DbJmP7B6B545m/uOEUGnfg9d0M=,tag:V5YmHAZD62djbXSx0w+Y4A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:1NxcDzPOtFVtsXCq,iv:GqumyRzffTNNeBHf/8a6xKNs/BR52mBn7u3W/FM5LXU=,tag:JPmGJFqsJHec6wLnlusBYg==,type:str]
    GOOGLE_STORAGE_BUCKET: ENC[AES256_GCM,data:IB/4bwVpicYu5AZ/tTN/uHgvtGQg/qgNBT62qmqWw/U=,iv:dgxEE1npNSBXkgwkFjI3krrlKRkXi0avzur5nIyVRfI=,tag:kwKdlXjk8gvg42akYJBuuQ==,type:str]
    GOOGLE_STORAGE_ACCESS_KEY: ENC[AES256_GCM,data:mQcGt9pwVSuq4nvRWyq6Rn1rlIn5iuKb2N6BJJSIzFi4V5gllXSIMEUM24eFwp1M5GOqu+50JjyXspLyXD8fvTdbG1WDkVz316guG677XD+mnMaMDXdBpsXmW3DJ3H3S6m2YDl1nwgtfggRDzu5KzIDgqaQrxDbg36fbwMmNYmpGFwbliT/HYPKdK79m/ZB9aXvkbQ4F85Kv0MfrhZeWH+YD4VCVA9SJdTN0DVDUGLMsimInv+QQMqpTghHRc30qXA85CKIZYRP6a62NLfZwbFlLPQIiql7nAwg6Mz+gGjU9WKYTCdXgqd+vb45TFiFU4hZRnC4fMswdJnOiiAbBIP59VZJOmTqPA1HolLSp/LyDm2oXYlkXjdhuf/Vgr7frWzCPF9fJgWXZy6FcPBbb/g==,iv:m4MwcS5RVumz9QUVeHcbkCMfkpvZ9RadkfRFAC/3mds=,tag:4mgWDUniehA0yC+x9d8xbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yyjdng93qch2ms6yygterjuwdu33n7tx67mr4f4y29l4ugkwumqtjzexm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRnVMckE5OS9XWWtqek9h
            VlJ0d3krbE1sQkUzTXM3QWtnS3lKWVNhajNRCldmNkQwN21vNVRSRTBzQ1ZJZ2xI
            L3BWdm1VMkZ1RXgweExJOUcxQ1lXRkEKLS0tIFZoakpiSDRuaFNiUmJSWm81MHdI
            VFBoMHVaQU5qVTMwTlhJU3A1dVNkdlkKKjYJOP/mHM4OmqudEbAEGqkr4HIUk9rt
            z3kQHUz0/ESUv47pg9oVcOAJTc4Nqd32Co9H+Sno3eRyBfFwuhxBKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-30T23:25:01Z"
    mac: ENC[AES256_GCM,data:aWmM1B1CEZ1ufLXe4NIfAHcyVDLdRyGDLYiDiE/rqQxResu4ToQdUoHHcPY9tuREMDwwHlVU4Z21xWla3i8K9mypwxyhSt69rs6EgGlsCVAlvYyoFbAs+qUDbWkvIeAvbAfyWmduGX+n+ItaMtBmRBpyZiPcb4wBObWiz6+HYAY=,iv:fe7mNLr5omsNRFATqEN1TYieuloLwbn8FbJT0JsVyFs=,tag:CU4o1AIbKsNBv77Vm6SObQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.1
