apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: pingpong
  name: hash-pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hash-pingpong
  template:
    metadata:
      labels:
        app: hash-pingpong
    spec:
      containers:
        - name: server
          image: maxmynter/devopsk8s-node-endpoint@sha256:5b84335feb34b8f21ab96b467eb11a377b0f996e5cef786c071f736e916485e1
          ports:
           - containerPort: 3000
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /ready
              port: 3000
          volumeMounts:
            - name: info
              mountPath: /etc/config
              readOnly: true
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: info
                key: message
      volumes:
      - name: info
        configMap: 
          name: info

---
apiVersion: v1
kind: Service
metadata:
  namespace: pingpong
  name: server-svc
spec:
  type: NodePort
  selector:
    app: hash-pingpong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
