apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: persisted-volume
          persistentVolumeClaim:
            claimName: persisted-claim
      containers:
        - name: backend
          imagePullPolicy: Always
          volumeMounts:
            - name: persisted-volume
              mountPath: /usr/src/app/cache
          image: maxmynter/devopsk8s-backend@sha256:ede38c90011818cdd25759e9a26651ab838fc580e377a6b0db5f6783903c0904
        - name: frontend
          image: maxmynter/devopsk8s-frontend@sha256:e0862043fad0fe5a54dd2ab3523d23bcdf93ccb79886df8b8988f9de718b973c
          ports:
            - containerPort: 80
