apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - name: http
      protocol: TCP
      port: 1234
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 3000
