apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
  namespace: project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
      - name: broadcaster
        image: TODO/BROADCASTER
        env:
          - name: NATS_ENDPOINT
            value: nats://my-nats:4222
          - name: DISCORD_WEBHOOK_URL
            valueFrom:
              secretKeyRef:
                name: discord-webhook-secret
                key: DISCORD_WEBHOOK_URL
