apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/config-map.yaml
- manifests/endpoint.yaml
- manifests/ingress.yaml
- manifests/pingpong.yaml
- postgres/manifests/postgres-service.yaml
- postgres/manifests/statefulset.yaml




images:
- name: PONG/PINGPONG
  newName: maxmynter/devopsk8s-pingpong
  newTag: d0b5324a769b7870b6249c55650d3816ea7bd651
- name: PONG/SERVER
  newName: maxmynter/devopsk8s-node-endpoint
  newTag: d0b5324a769b7870b6249c55650d3816ea7bd651
- name: PONG/STATEFULSET
  newName: maxmynter/devopsk8s-postgres
  newTag: d0b5324a769b7870b6249c55650d3816ea7bd651
