apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/config-map.yaml
- manifests/endpoint.yaml
- manifests/ingress.yaml
- manifests/pingpong.yaml
- postgres/manifests/postgres-service.yaml
- postgres/manifests/statefulset.yaml




images:
- name: PONG/PINGPONG
  newName: maxmynter/devopsk8s-pingpong
  newTag: def2cb05be8062bfa34690276533513abbec5c92
- name: PONG/SERVER
  newName: maxmynter/devopsk8s-node-endpoint
  newTag: def2cb05be8062bfa34690276533513abbec5c92
- name: PONG/STATEFULSET
  newName: maxmynter/devopsk8s-postgres
  newTag: def2cb05be8062bfa34690276533513abbec5c92
