apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/config-map.yaml
- manifests/endpoint.yaml
- manifests/ingress.yaml
- manifests/pingpong.yaml
- postgres/manifests/postgres-service.yaml
- postgres/manifests/statefulset.yaml




images:
- name: PONG/PINGPONG
  newName: maxmynter/devopsk8s-pingpong
  newTag: 77324721440cfdc958c8ae6e70de987cb67f0e05
- name: PONG/SERVER
  newName: maxmynter/devopsk8s-node-endpoint
  newTag: 77324721440cfdc958c8ae6e70de987cb67f0e05
- name: PONG/STATEFULSET
  newName: maxmynter/devopsk8s-postgres
  newTag: 77324721440cfdc958c8ae6e70de987cb67f0e05
