apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pingpong-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maxmynter/devopsk8s
    path: ex4.08/project_v2.0/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
