apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki-todo
  namespace: project
spec:
  schedule: "9 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-todo
            image: maxmynter/devopsk8s-cronjob@sha256:e788ff8680b5a8ca2ae094a0286778c7caef2b25ce573a7246fbb1717920cd7e
            env:
            - name: BACKEND_URL
              value: "http://todo-backend-svc:2345"
          restartPolicy: OnFailure
