apiVersion: v1
kind: Service
metadata:
  name: node-api-loadbalancer
  namespace: project
spec:
  type: LoadBalancer
  selector:
    app: todo-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000

