apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: c-logs
          image: maxmynter/c-log-k8s-mooc
