apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-check
  namespace: project
spec:
  metrics:
  - name: cpu-usage
    interval: 1m
    count: 15
    failureLimit: 1
    successCondition: result < 0.05  # Threshold value for CPU usage percentage
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1702-prometheus.prometheus.svc.cluster.local:9090
        query: |
          sum(rate(container_cpu_usage_seconds_total{namespace="project"}[1m])) by (namespace)
