apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki-todo
  namespace: project
spec:
  schedule: "9 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-todo
            image: TODO/CRONJOB
            env:
            - name: BACKEND_URL
              value: "http://todo-backend-svc:2345"
          restartPolicy: OnFailure
